Myshop/Myshop/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    path('', include('basket.urls')),
    path("django-admin/", admin.site.urls),
    path("admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),
    path('', include('home.urls')),

]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

Myshop/basket/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views
from . import basket
#from home.models import Product
app_name = 'basket'

# router = routers.DefaultRouter()
# router.register(r'basket', )


urlpatterns = [
    # path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls')),
    path('basket', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
    path('^send/', views.send_tg, name='send'),
]

Myshop/home/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from . import views

urlpatterns = [
    # path('size/', views.add_size, name='size'),

]

Myshop/home/models.py
from django.db import models
from modelcluster.fields import ParentalKey
from wagtail.core.models import Page, Orderable
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.contrib.settings.models import BaseSetting, register_setting

from parscart.utils import send_telegram_message


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter()


class HomePage(Page):
    def get_context(self, request):
        context = super().get_context(request)

        context['products'] = Product.objects.child_of(self).live()

        return context


class Product(Page):
    sku = models.CharField(max_length=255)
    short_description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    #quantity = models.IntegerField(null=False)
    products = ProductManager()

    content_panels = Page.content_panels + [
        FieldPanel('sku'),
        FieldPanel('price'),
        ImageChooserPanel('image'),
        FieldPanel('short_description'),
        InlinePanel('custom_fields', label='Custom fields'),
    ]

    def get_context(self, request):
        context = super().get_context(request)
        fields = []
        sizes = []
        for f in self.custom_fields.get_object_list():
            if f.options:
                f.options_array = f.options.split('|')
                fields.append(f)
            else:
                fields.append(f)

        context['custom_fields'] = fields
        return context

    def send_offer_telegram(self):
        message = (
            f'Представьтесь: {self.price}\n'
            )
        if self.price:
            message += f'Сообщение: {self.price}\n'
        send_telegram_message(message)


class ProductCustomField(Orderable):
    product = ParentalKey(Product, on_delete=models.CASCADE, related_name='custom_fields')
    name = models.CharField(max_length=255)
    options = models.CharField(max_length=500, null=True, blank=True)
    size = models.CharField(max_length=10, null=True)
    panels = [
        FieldPanel('name'),
        FieldPanel('options'),
    ]


@register_setting
class SnipcartSettings(BaseSetting):
    api_key = models.CharField(
        max_length=255,
        help_text='Your Snipcart public API key'
    )

Myshop/basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .basket import Basket
from home.models import Product
import requests


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        print(request.POST)
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)
        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def send_tg(request):
    product = Product()
    basket = Basket(request)

    basket.send_telegram_message()
    return render(request, 'basket/summary.html')



#
#
# def send_offer_telegram():
#     message = (
#         f'price: {Product.price}\n'
#         f'product: {Product.sku}\n'
#         )
#     send_telegram_message(message)

Myshop/search/views.py
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.template.response import TemplateResponse

from wagtail.models import Page
from wagtail.search.models import Query


def search(request):
    search_query = request.GET.get("query", None)
    page = request.GET.get("page", 1)

    # Search
    if search_query:
        search_results = Page.objects.live().search(search_query)
        query = Query.get(search_query)

        # Record hit
        query.add_hit()
    else:
        search_results = Page.objects.none()

    # Pagination
    paginator = Paginator(search_results, 10)
    try:
        search_results = paginator.page(page)
    except PageNotAnInteger:
        search_results = paginator.page(1)
    except EmptyPage:
        search_results = paginator.page(paginator.num_pages)

    return TemplateResponse(
        request,
        "search/search.html",
        {
            "search_query": search_query,
            "search_results": search_results,
        },
    )

Myshop/Myshop/templates/base.html
{% load static wagtailcore_tags wagtailuserbar %}
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns:basket="http://www.w3.org/1999/xhtml">


    <head>

       <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
        {% load  static  wagtailsettings_tags %}
{% get_settings %}

{# Global stylesheets #}

<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-exp.min.css">
<link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre-icons.min.css">

{# Snipcart #}

{% if settings.home.SnipcartSettings.api_key %}
         <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>


        <script src="https://cdn.snipcart.com/scripts/2.0/snipcart.js" id="snipcart" data-api-key="{{ settings.home.SnipcartSettings.api_key }}"></script>
    <link href="https://cdn.snipcart.com/themes/2.0/base/snipcart.min.css" type="text/css" rel="stylesheet" />
{% endif %}
        <meta charset="utf-8" />
        <title>
            {% block title %}
            {% if page.seo_title %}{{ page.seo_title }}{% else %}{{ page.title }}{% endif %}
            {% endblock %}
            {% block title_suffix %}
            {% wagtail_site as current_site %}
            {% if current_site and current_site.site_name %}- {{ current_site.site_name }}{% endif %}
            {% endblock %}
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {# Force all links in the live preview panel to be opened in a new tab #}
        {% if request.in_preview_panel %}
        <base target="_blank">
        {% endif %}

        {# Global stylesheets #}
        <link rel="stylesheet" type="text/css" href="{% static 'css/Myshop.css' %}">

        {% block extra_css %}
        {# Override this in templates to add extra stylesheets #}


    </head>
<body class="nav"><nav>
    <div class="container">
      <nav class="navbar navbar-expand-lg main-nav px-0">
        <a class="navbar-brand" href="static/media/cats.jpg">
					      <img src="{% static 'static/media/cats.jpg' %}" >
					    </a>

        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto text-uppercase f1">
            <li>
              <a href="/" class="active active-first">home</a>
            </li>
            <li>
              <a href="#about">about us</a>
            </li>
            <li>
              <a href="#service">services</a>
            </li>
            <li>
              <a href="#project">projects</a>
            </li>
            <li>
              <a href="#team">team</a>
            </li>
            <li>
              <a href="#testimony">testimonils</a>
            </li>
            <li>
              <a type="button" role="button" href="{% url "basket:basket_summary" %}"
                class="btn btn-outline-secondary">
                <div id="basket-qty" class="d-inline-flex">1</div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>basket</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    <!-- /.container -->


    </nav>
</body>

    <body class="body">

{% wagtailuserbar %}

<div class="container grid-lg">

{% block content %}{% endblock %}
        <!-- Snipcart summary and View cart button -->
        <section class="navbar-section snipcart-summary">
            <div class="input-group input-line">

            </div>
        </section>
</div>

    </body>

</html>

{% endblock %}

Myshop/Myshop/templates/basket/summary.html
{% extends "base.html" %}
{% load static %}
{% block title %}Basket Summary{% endblock %}
{% block content %}
{% load wagtailimages_tags wagtailcore_tags %}

<main class="pt-5">
  <div class="container">
    <h1 class="h5">Shopping basket</h1>
    {% for item in basket %}
    {% with product=item.product %}
    <div data-index="{{product.id}}" class="row mb-4 border product-item">
      <div class="col-md-3 col-lg-2 order-md-first bg-light">

          {% image page.image fill-320x240 %}

      </div>
      <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
        <a href="{{ product.get_absolute_url }}" class="text-decoration-none text-reset">
          <h1 class="h5 pt-2">{{ product.title }}</h1>
        </a>
        <div class="border">
          <div class="col border-bottom">
            <div class="row p-3">

              <div class="col-6 text-end"><span class="h6 fw-bold">${{ product.price }}</span></div>
            </div>
          </div>
          <div class="col">
            <div class="row p-3">
              <div class="col-12">
                <label for="select">Qty</label>
                <select id="select{{product.id}}">
                  <option selected>
                    {{item.qty}}
                  </option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm update-button">
                  Update
                </button>
                <button type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-outline-secondary btn-sm delete-button">
                  Delete
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endwith %}
    {% endfor %}
    <div class="col-12 text-end">
      <div class="h6 fw-bold">Sub Total: $<div id="subtotal" class="d-inline-flex">{{basket.get_total_price}}</div></div>
    </div>



      <button type="submit" onclick="location.href='{% url 'basket:send' %}'"    class="btn btn-outline-secondary btn-sm update-button">Order</button>

  </div>
</main>

<script>

  // Delete Item
  $(document).on('click', '.delete-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',

      data: {
        productid: $(this).data('index'),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })

  // Update Item
  $(document).on('click', '.update-button', function (e) {
    e.preventDefault();
    var prodid = $(this).data('index');
    $.ajax({
      type: 'POST',

      data: {
        productid: $(this).data('index'),
        productqty: $('#select' + prodid + ' option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
        document.getElementById("subtotal").innerHTML = json.subtotal
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}

Myshop/home/templates/home/home_page.html
{% extends "base.html" %}
{% load wagtailimages_tags %}
{% load static %}
<html>

<body>
{% block content %}
    <h1>
        Welcome to our store
    </h1>

    <div class="columns">

        {% for product in products %}
            <div class="column col-6">
                <div>  .</div>
                <div class="card">
                    <div class="card-image">
                        {% image product.image max-500x200 as tmp_image %}
                        <img src="{{ tmp_image.url }}" alt="" class="img-fluid mx-auto d-block">
                    </div>
                    <div class="card-header">
                        <a href="{{ product.get_url }}" class="btn btn-primary float-right">
                            <i class="icon icon-plus"></i>
                        </a>
                        <div class="card-title h5">
                            {{ product.title }}
                        </div>
                    </div>
                    <div class="card-body">
                        {{ product.description }}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>>

Myshop/home/templates/home/product.html
{% extends "base.html" %}
{% load wagtailimages_tags %}

{% block content %}
<header>

    </header>
    <div class="container grid-lg">
        <div class="columns">
            <div class="column col-4">
                {% image page.image max-300x300 as temp_image %}
                <img src="{{ temp_image.url }}" alt="" />
            </div>
            <div class="column col-8">
                <h1>
                    {{ page.title }}
                </h1>

                <p>
                    {{ page.short_description }}

                </p>
<p>
                <b >size:</b>
                <select name="size" class="form-control">
                    <option value="1">30</option>
                    <option value="2">36</option>
                    <option value="3">40</option>
                </select>
            </p>
            <p>
                <b for="select">qty:</b>
                <select id="select" class="form-control">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                </select>
            </p>
<!--                  <p><b>Size:</b>-->
<!--                    <select name="sizes" class="form-control">-->
<!--                    {% for res in showsize %}-->
<!--                        <option value="{{res.id}}">{{res.size}}</option>-->
<!--                    {% endfor %}-->
<!--                    </select>-->
<!--                  </p>-->

                <p>
                    {% for f in custom_fields %}
                        {% if f.options_array|length > 0 %}
                            <div class="form-group">
                                <label class="form-label" for="{{ f.name|lower }}">
                                    {{ f.name }}

                                </label>
                                <select class="form-select custom-field-select" id="{{ f.name|lower }}" data-field="{{ forloop.counter }}">
                                    {% for opt in f.options_array %}
                                        <option>
                                            {{ opt }}
                                        </option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                    {% endfor %}
                </p> <h1>
                    {{ page.price }}$
                </h1>
          <div class="col-6 text-end">
              <button type="button" id="add-button" value="{{ page.id }}" class="btn btn-secondary btn-sm">Add to
                  basket</button></div>
        </div>
    </div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                console.log(json)
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

        {% endblock %}

Myshop/search/templates/search/search.html
{% extends "base.html" %}
{% load static wagtailcore_tags %}

{% block body_class %}template-searchresults{% endblock %}

{% block title %}Search{% endblock %}

{% block content %}
<h1>Search</h1>

<form action="{% url 'search' %}" method="get">
    <input type="text" name="query"{% if search_query %} value="{{ search_query }}"{% endif %}>
    <input type="submit" value="Search" class="button">
</form>

{% if search_results %}
<ul>
    {% for result in search_results %}
    <li>
        <h4><a href="{% pageurl result %}">{{ result }}</a></h4>
        {% if result.search_description %}
        {{ result.search_description }}
        {% endif %}
    </li>
    {% endfor %}
</ul>

{% if search_results.has_previous %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.previous_page_number }}">Previous</a>
{% endif %}

{% if search_results.has_next %}
<a href="{% url 'search' %}?query={{ search_query|urlencode }}&amp;page={{ search_results.next_page_number }}">Next</a>
{% endif %}
{% elif search_query %}
No results found
{% endif %}
{% endblock %}